### ISSUE TITLE
Student management system

### ISSUE THREAD

**Issue by Shimdu** [Shimdu/student_manage#1]
Hi, Jons:
This system is a student management system which I have done for my Graduation Design. Please take a look. If you think this system is ok, please contact me, thank you.

-----------------

There are three roles of the system: student, teacher and manager (manager is a higher level of teacher).
The main functions of students are selecting courses and inquiring grades.
The main functions of teachers are managing students and entering grades for students.
The main functions of managers are managing courses and managing teachers. (and also include all teacher's functions)

Username & Password for logging the system:
student: `054321` &`12345`
teacher: `012345` & `12345`
manager: `012312` & `12345`

----------------

Please take a look, thank you! @jslemmer

**Comment by 9sa6c** [comment]
Host the website some where, so I can see the site in action.
You can use the server I gave you before.

**Comment by Shimdu** [comment]
I have put it online, and the website is `http://2201513130118.instantcloud.cn/student_manage`.
But there is still some problems:
![image](https://user-images.githubusercontent.com/37894211/41810615-18878856-7734-11e8-8bd1-2b0dff6ee8e1.png)
Could you tell me how to fix it?

**Comment by 9sa6c** [comment]
It can not find some file. check what file does not load (404).

Best regards,

Jons Slemmer

**Comment by Shimdu** [comment]
OK, I have done it. The system looks almost ok. Please check it, thank you.
If the system meets your expectations, could you please introduce a job to me? Thank you.
By the way, I'm still working on the small challenge which you gave to me (Distance between two points). I will figure out how to cross obstacles.
